services:
  dev:
    build: .
    container_name: cs242
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: tail -f /dev/null