services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  dev:
    build: .
    container_name: cs242
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    command: tail -f /dev/null